### ISSUE TITLE
Service pattern

### ISSUE THREAD

**Issue by pablomaurer** [nolanlawson/pouchdb-ionic#1]
So here you are hiding the interesting stuff =)

Maybe i'm doing something wrong, but i got an error and the [error page](https://docs.angularjs.org/error/$injector/unpr?p0=) said you cannot have `$scope` in a `service`. 

``` js
angular.module('myModule', [])
.service('MyController', ['$scope', function($scope) {
  // This controller throws an unknown provider error because
  // a scope object cannot be injected into a service.
}]);
```

**Comment by nolanlawson** [comment]
Maybe this is something they changed in a new version of angular. I use this pattern in npm browser.

**Comment by ptgamr** [comment]
There shouldn't be a $scope in Angular's service I think. As service are design to be singleton, $scope is the thing that tight to $controller. But, $rootScope is ok I think.

I prefer implementing it this way: https://github.com/ptgamr/soundcloudify/blob/pouchdb/app/scripts/services/PouchDB.js

**Comment by chrisschaub** [comment]
Yeah, finding same issue with Angular and Ionic. $scope is not allowed in services.

**Comment by nolanlawson** [comment]
Would happily accept a PR with suggested changes. :)

**Comment by nolanlawson** [comment]
I've fixed the example. I think this was just me misremembering how to use Angular. Been spending too much time in React and Ember land recently!
